const typography = {
  fontFamily: [
    "Quicksand",
    "Montserrat",
    "Inter",
    "-apple-system",
    "BlinkMacSystemFont",
    '"Segoe UI"',
    '"Helvetica Neue"',
    "Arial",
    "sans-serif",
    '"Apple Color Emoji"',
    '"Segoe UI Emoji"',
    '"Segoe UI Symbol"',
  ].join(","),
  fontSize: 14,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 600,
  h1: {
    fontFamily: ["Quicksand", "sans-serif"],
    fontStyle: "normal",
    fontSize: "24px",
    fontWeight: 600,
    lineHeight: "38px",
    letterSpacing: "-0.219429px",
    color: "#4D4D4D",
  },
  h2: {
    fontFamily: ["Quicksand", "sans-serif"],
    fontStyle: "normal",
    fontSize: "18px",
    fontWeight: 600,
    lineHeight: "34px",
    letterSpacing: "-0.233333px",
    color: "#4D4D4D",
  },
  h3: {
    fontFamily: ["Quicksand", "sans-serif"],
    fontStyle: "normal",
    fontSize: "24px",
    fontWeight: 400,
    lineHeight: "29px",
    color: "#4D4D4D",
  },
  h4: {
    fontFamily: ["Quicksand", "sans-serif"],
    fontStyle: "normal",
    fontSize: "20px",
    fontWeight: 400,
    lineHeight: "24px",
    letterSpacing: "0.0411765px",
    color: "#4D4D4D",
  },
  h5: {
    fontFamily: ["Quicksand", "sans-serif"],
    fontStyle: "normal",
    fontSize: "16px",
    fontWeight: 400,
    lineHeight: "24px",
    color: "#4D4D4D",
  },
  h6: {
    fontFamily: ["Quicksand", "sans-serif"],
    fontStyle: "normal",
    fontSize: "14px",
    fontWeight: 400,
    lineHeight: "20px",
    letterSpacing: "0.0595px",
    color: "#4D4D4D",
  },
  body1: {
    fontFamily: ["Quicksand", "sans-serif"],
    fontStyle: "normal",
    fontSize: "14px",
    fontWeight: 400,
    lineHeight: "20px",
    letterSpacing: "0.1px",
    color: "#4D4D4D",
  },
  body2: {
    fontFamily: ["Quicksand", "sans-serif"],
    fontStyle: "normal",
    fontSize: "14px",
    fontWeight: 400,
    lineHeight: "20px",
    letterSpacing: "0.1px",
    color: "#4D4D4D",
  },
  button: {
    fontFamily: ["Quicksand", "sans-serif"],
    fontStyle: "normal",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "20px",
    letterSpacing: "0.2px",
    color: "#4D4D4D",
    textTransform: "initial",
  },
  tableHeader: {
    fontFamily: ["Quicksand", "sans-serif"],
    fontStyle: "normal",
    fontSize: "16px",
    fontWeight: 500,
    lineHeight: "24px",
    color: "#4D4D4D",
  },
  subTitle: {
    fontFamily: ["Quicksand", "sans-serif"],
    fontStyle: "normal",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "21px",
    letterSpacing: "0.09px",
    color: "#4D4D4D",
  },
  subText: {
    fontFamily: ["Quicksand", "sans-serif"],
    fontStyle: "normal",
    fontSize: "8px",
    fontWeight: 400,
    lineHeight: "10px",
    letterSpacing: "0.01px",
    color: "#999999",
  },
};

export default typography;
